/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.Basic

/-!
# Open ideals of a Huber ring

Fix a pair of definition `(A₀, I)` for a Huber ring `A`. The neighbourhoods of zero that are
cofinal are the *images* of the powers `Iⁿ` in `A`, not the ideals they generate — an ideal span
can be much larger than the additive subgroup it is spanned by. What makes the ideal statement
work is that an *ideal* of `A` containing the image of `Iⁿ` automatically contains its span
`(I · A)ⁿ`. So an ideal of `A` is open exactly when it contains one of those powers, and since
`I · A` is finitely generated that is the same as asking `I · A` to lie in its radical.

## Main results

* `TauCeti.Huber.PairOfDefinition.extendedIdealOfDefinition_pow`: the powers of `I · A`
  (defined in `TauCeti/RingTheory/Huber/Basic.lean`) are generated by the basic neighbourhoods
  of zero.
* `TauCeti.Huber.PairOfDefinition.isOpen_iff_exists_pow_le`: an ideal of `A` is open exactly when
  it contains a power of `I · A`.
* `TauCeti.Huber.PairOfDefinition.isOpen_iff_le_radical`: an ideal of `A` is open exactly when its
  radical contains `I · A`.
* `TauCeti.Huber.PairOfDefinition.isOpen_mul`: the product of two open ideals is open — the
  powers of `I · A` witnessing each add.
* `TauCeti.Huber.PairOfDefinition.isOpen_span_mul`: the span of a pointwise product of sets is
  open when the two spans are.
* `TauCeti.Huber.PairOfDefinition.isOpen_span_insert_mul_insert`: its `Finset` form with the two
  denominators adjoined — the admissibility half of Wedhorn Remark 7.30(5).
* `TauCeti.Huber.PairOfDefinition.exists_forall_mem_idealImage_exists_sum_eq`: the sharpening of
  those criteria that the valuation theory needs — if a finite set `T` spans an open ideal, then
  a basic neighbourhood of zero consists of `T`-combinations whose *coefficients* lie in the
  image of the ideal of definition, hence are topologically nilpotent.
* `TauCeti.Huber.IsTateRing.isOpen_iff_eq_top`: an ideal of a Tate ring is open exactly when it is
  the whole ring.

## Provenance

AINTLIB formalises this same layer and was consulted for the choice of results; the statements,
names and proofs here are independent of it. Its `HuberRings.lean` carries the extension `I · A`
as `PairOfDefinition.idealOfDefinition` — a name this development gives to the ideal of `A₀`
itself, so `extendedIdealOfDefinition` is used here instead — with `idealOfDefinition_fg` proved,
as `fg_extendedIdealOfDefinition` is, by `Ideal.FG.map`. Its
`projects/AdicSpaces/Adic spaces/OpenIdeals.lean` is headed "We prove Lemma 6.6 … of
[Wedhorn, *Adic Spaces*]" and reaches the radical criterion as
`ideal_isOpen_iff_topologicalNilradical_le_radical`, phrased through the topological nilradical
and hypothesising a finitely generated ideal of definition; the form below instead names the pair
of definition and routes the whole lemma through `Ideal.map_pow`.

The product lemmas below are independent of it in a stronger sense: AINTLIB's
`ValuationSpectrum.HasRationalPresentation` (`projects/AdicSpaces/Adic spaces/RationalSubsets.lean`)
records only that a set *is* some `R(T/s)`, with no openness condition on `T A`, so its
`HasRationalPresentation.inter` is the set-level identity alone. Its blueprint asserts in prose
that "the numerator family of the product still generates an open ideal", but that half is not
formalised there and nothing could be ported.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], Lemma 6.6 and Remark 7.30(5).
* [AINTLIB](https://github.com/CBirkbeck/AINTLIB), branch `dev/adic-spaces`,
  `projects/AdicSpaces/Adic spaces/OpenIdeals.lean` and `HuberRings.lean`.
-/

public section

namespace TauCeti.Huber

namespace PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A]

/-- The `n`-th power of `I · A` is generated by the `n`-th basic neighbourhood of zero: the
image `TauCeti.Huber.PairOfDefinition.idealImage n` of `Iⁿ` in `A`. -/
theorem extendedIdealOfDefinition_pow (P : PairOfDefinition A) (n : ℕ) :
    P.extendedIdealOfDefinition ^ n = Ideal.span (P.idealImage n : Set A) := by
  rw [P.coe_idealImage, ← Subring.coe_subtype, ← Ideal.map_span, Ideal.span_eq,
    P.extendedIdealOfDefinition_def, ← Ideal.map_pow]

variable [IsTopologicalRing A]

/-- Wedhorn Lemma 6.6: an ideal of a Huber ring is open exactly when it contains a power of the
ideal `I · A` generated by an ideal of definition. -/
theorem isOpen_iff_exists_pow_le (P : PairOfDefinition A) (a : Ideal A) :
    IsOpen (a : Set A) ↔ ∃ n : ℕ, P.extendedIdealOfDefinition ^ n ≤ a := by
  constructor
  · intro ha
    obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp (ha.mem_nhds a.zero_mem)
    exact ⟨n, by rw [P.extendedIdealOfDefinition_pow, Ideal.span_le]; exact hn⟩
  · rintro ⟨n, hn⟩
    rw [P.extendedIdealOfDefinition_pow, Ideal.span_le] at hn
    exact AddSubgroup.isOpen_mono (H₂ := a.toAddSubgroup) hn (P.isOpen_idealImage n)

/-- Wedhorn Lemma 6.6, radical form: an ideal of a Huber ring is open exactly when its radical
contains the ideal `I · A` generated by an ideal of definition. -/
theorem isOpen_iff_le_radical (P : PairOfDefinition A) (a : Ideal A) :
    IsOpen (a : Set A) ↔ P.extendedIdealOfDefinition ≤ a.radical := by
  rw [P.isOpen_iff_exists_pow_le a]
  exact ⟨fun ⟨n, hn⟩ _ hx ↦ ⟨n, hn (Ideal.pow_mem_pow hx n)⟩,
    fun h ↦ Ideal.exists_pow_le_of_le_radical_of_fg h P.fg_extendedIdealOfDefinition⟩

/-- **The product of two open ideals is open.** If `a` contains `(I · A)ⁿ` and `b` contains
`(I · A)ᵐ`, then `a * b` contains `(I · A)ⁿ⁺ᵐ`. Note this is a statement about the *product*
ideal, which is smaller than the intersection: openness survives the smaller of the two. -/
theorem isOpen_mul (P : PairOfDefinition A) {a b : Ideal A} (ha : IsOpen (a : Set A))
    (hb : IsOpen (b : Set A)) : IsOpen ((a * b : Ideal A) : Set A) := by
  obtain ⟨n, hn⟩ := (P.isOpen_iff_exists_pow_le a).mp ha
  obtain ⟨m, hm⟩ := (P.isOpen_iff_exists_pow_le b).mp hb
  refine (P.isOpen_iff_exists_pow_le _).mpr ⟨n + m, ?_⟩
  rw [pow_add]
  exact Ideal.mul_mono hn hm

open scoped Pointwise in
/-- **A span over a pointwise product of sets is open** when the two factors' spans are, since
`Ideal.span_mul_span` identifies it with the product ideal. This is the form Wedhorn's
Remark 7.30(5) needs: the numerator set of an intersection of rational subsets is a pointwise
product. -/
theorem isOpen_span_mul (P : PairOfDefinition A) {S T : Set A}
    (hS : IsOpen (Ideal.span S : Set A)) (hT : IsOpen (Ideal.span T : Set A)) :
    IsOpen (Ideal.span (S * T) : Set A) := by
  rw [← Ideal.span_mul_span]
  exact P.isOpen_mul hS hT

open scoped Classical Pointwise in
/-- **The numerator set of an intersection of rational subsets spans an open ideal.** Adjoining
each denominator only enlarges a span, so this is `isOpen_span_mul` after two applications of
Mathlib's `Ideal.isOpen_of_isOpen_subideal`. It is the admissibility half of Wedhorn
Remark 7.30(5): the set identity
`TauCeti.ValuationSpectrum.rationalSubset_inter` presents the intersection with numerators
`insert s₁ T₁ * insert s₂ T₂`, and a rational subset is one whose numerator ideal is open. -/
theorem isOpen_span_insert_mul_insert (P : PairOfDefinition A) {T₁ T₂ : Finset A} {s₁ s₂ : A}
    (hT₁ : IsOpen (Ideal.span (T₁ : Set A) : Set A))
    (hT₂ : IsOpen (Ideal.span (T₂ : Set A) : Set A)) :
    IsOpen (Ideal.span ((insert s₁ T₁ * insert s₂ T₂ : Finset A) : Set A) : Set A) := by
  rw [Finset.coe_mul]
  exact P.isOpen_span_mul (Ideal.isOpen_of_isOpen_subideal (Ideal.span_mono (by simp)) hT₁)
    (Ideal.isOpen_of_isOpen_subideal (Ideal.span_mono (by simp)) hT₂)

/-- **An open numerator ideal swallows a whole neighbourhood of zero with coefficients that are
themselves topologically nilpotent.** If the ideal generated by a finite set `T` is open, then
some basic neighbourhood `Iⁿ` of zero consists of combinations `∑ t ∈ T, t * w t` whose
coefficients `w t` lie in the image of the ideal of definition itself.

This sharpens `TauCeti.Huber.PairOfDefinition.isOpen_iff_exists_pow_le`, which only places `Iⁿ`
inside the ideal `T · A` and so offers coefficients in `A` about which nothing is known. The
sharpening is what a valuation-theoretic estimate needs: over a point of the adic spectrum a
coefficient in `A` carries no bound at all, whereas one in `I` has value `< 1` (an element of `I`
is topologically nilpotent). Thus the resulting combination is strictly dominated by any chosen
nonzero common upper bound for the values `v t`, such as a rational subset's denominator. -/
theorem exists_forall_mem_idealImage_exists_sum_eq (P : PairOfDefinition A) (T : Finset A)
    (hT : IsOpen (Ideal.span (T : Set A) : Set A)) :
    ∃ n : ℕ, ∀ a ∈ P.idealImage n, ∃ w : A → A,
      (∀ t ∈ T, w t ∈ P.idealImage 1) ∧ ∑ t ∈ T, t * w t = a := by
  classical
  obtain ⟨m, hm⟩ := (P.isOpen_iff_exists_pow_le _).mp hT
  obtain ⟨G, hG⟩ := P.fg_idealOfDefinition.pow (n := m)
  -- Each generator of `Iᵐ` is a `T`-combination, with coefficients `d z` in `A`.
  have hgen : ∀ z : P.ringOfDefinition, ∃ d : A → A, z ∈ G → ∑ t ∈ T, t * d t = (z : A) := by
    intro z
    by_cases hz : z ∈ G
    · have hz' : (z : A) ∈ Ideal.span (T : Set A) * (⊤ : Ideal A) := by
        rw [Ideal.mul_top]
        refine hm ?_
        rw [P.extendedIdealOfDefinition_pow]
        exact Ideal.subset_span ((P.mem_idealImage m).mpr ⟨z, hG ▸ Ideal.subset_span hz, rfl⟩)
      obtain ⟨d, -, hd⟩ := exists_sum_eq_of_mem_span_mul T (⊤ : Ideal A) hz'
      exact ⟨d, fun _ ↦ hd⟩
    · exact ⟨0, fun h ↦ absurd h hz⟩
  choose d hd using hgen
  -- Each coefficient carries a high enough power of `I` back into `I`.
  have habs : ∀ (z : P.ringOfDefinition) (t : A), ∃ N : ℕ,
      ∀ x ∈ P.idealImage N, d z t * x ∈ P.idealImage 1 := by
    intro z t
    have h0 : (0 : A) ∈ (d z t * ·) ⁻¹' (P.idealImage 1 : Set A) := by simp
    obtain ⟨N, -, hN⟩ := P.hasBasis_nhds_zero.mem_iff.mp
      (((P.isOpen_idealImage 1).preimage (continuous_const_mul (d z t))).mem_nhds h0)
    exact ⟨N, fun x hx ↦ hN hx⟩
  choose N hN using habs
  set K : ℕ := G.sup fun z ↦ T.sup (N z) with hK
  refine ⟨m + K, fun a ha ↦ ?_⟩
  obtain ⟨y, hy, rfl⟩ := (P.mem_idealImage (m + K)).mp ha
  have hy' : y ∈ Ideal.span (G : Set P.ringOfDefinition) * P.idealOfDefinition ^ K := by
    rw [hG, ← pow_add]
    exact hy
  obtain ⟨c, hc, hsum⟩ := exists_sum_eq_of_mem_span_mul G (P.idealOfDefinition ^ K) hy'
  have hcmem : ∀ z : P.ringOfDefinition, (c z : A) ∈ P.idealImage K :=
    fun z ↦ (P.mem_idealImage K).mpr ⟨c z, hc z, rfl⟩
  refine ⟨fun t ↦ ∑ z ∈ G, d z t * (c z : A), fun t ht ↦ ?_, ?_⟩
  · refine sum_mem fun z hz ↦ hN z t _ (P.idealImage_anti ?_ (hcmem z))
    exact (Finset.le_sup (f := N z) ht).trans (Finset.le_sup (f := fun z ↦ T.sup (N z)) hz)
  · have hz : ∀ z ∈ G, ∑ t ∈ T, t * (d z t * (c z : A)) = (z : A) * (c z : A) := by
      intro z hzG
      rw [← hd z hzG, Finset.sum_mul]
      exact Finset.sum_congr rfl fun t _ ↦ by ring
    calc ∑ t ∈ T, t * ∑ z ∈ G, d z t * (c z : A)
        = ∑ t ∈ T, ∑ z ∈ G, t * (d z t * (c z : A)) :=
          Finset.sum_congr rfl fun t _ ↦ Finset.mul_sum _ _ _
      _ = ∑ z ∈ G, ∑ t ∈ T, t * (d z t * (c z : A)) := Finset.sum_comm
      _ = ∑ z ∈ G, (z : A) * (c z : A) := Finset.sum_congr rfl hz
      _ = ((∑ z ∈ G, z * c z : P.ringOfDefinition) : A) := by push_cast; rfl
      _ = (y : A) := by rw [hsum]

end PairOfDefinition

section Tate

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- An open ideal in a Tate ring is the whole ring `⊤`. -/
theorem IsTateRing.eq_top_of_isOpen [IsTateRing A] {J : Ideal A}
    (hJ : IsOpen (J : Set A)) : J = ⊤ := by
  obtain ⟨ϖ, hϖ⟩ := IsTateRing.exists_isPseudoUniformizer (A := A)
  obtain ⟨n, hn⟩ := hϖ.isTopologicallyNilpotent.exists_pow_mem_of_mem_nhds (hJ.mem_nhds J.zero_mem)
  exact Ideal.eq_top_of_isUnit_mem J hn (hϖ.isUnit.pow n)

/-- In a Tate ring, an ideal is open if and only if it is the whole ring `⊤`. -/
@[simp]
theorem IsTateRing.isOpen_iff_eq_top [IsTateRing A] (J : Ideal A) :
    IsOpen (J : Set A) ↔ J = ⊤ :=
  ⟨IsTateRing.eq_top_of_isOpen, fun h ↦ h.symm ▸ isOpen_univ⟩

/-- **No maximal ideal of a Tate ring is open.** An open ideal is `⊤` and a maximal ideal is
proper, so the two cannot meet. This is the sharp form: one maximal ideal is enough, and no
hypothesis about the others is needed. -/
theorem IsTateRing.not_isOpen_of_isMaximal [IsTateRing A] {𝔪 : Ideal A} (h𝔪 : 𝔪.IsMaximal) :
    ¬ IsOpen (𝔪 : Set A) :=
  fun h ↦ h𝔪.ne_top ((IsTateRing.isOpen_iff_eq_top 𝔪).mp h)

/-- **Requiring every maximal ideal to be open forces a Tate ring to be zero**, since a nonzero
ring has a maximal ideal and `IsTateRing.not_isOpen_of_isMaximal` says that one cannot be open.

Worth naming because that hypothesis is easy to write down and impossible to satisfy. Wedhorn's
Proposition 7.52(2) carries it, and the statements that inherit it — among them
`TauCeti.ValuationSpectrum.isUnit_of_forall_not_vle_zero` — are therefore vacuous on exactly the
affinoid rings they are meant for, since those are Tate.

Note the quantifier is doing real work: over the zero ring there is no maximal ideal, so `hmax`
holds and the conclusion holds too. Dropping it to a single maximal ideal would give a statement
whose own hypotheses are contradictory. -/
theorem IsTateRing.subsingleton_of_forall_isMaximal_isOpen [IsTateRing A]
    (hmax : ∀ 𝔪 : Ideal A, 𝔪.IsMaximal → IsOpen (𝔪 : Set A)) : Subsingleton A := by
  rw [← not_nontrivial_iff_subsingleton]
  intro _
  obtain ⟨𝔪, h𝔪⟩ := Ideal.exists_maximal A
  exact IsTateRing.not_isOpen_of_isMaximal h𝔪 (hmax 𝔪 h𝔪)

end Tate

end TauCeti.Huber
