/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.GenericPoint
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Basic

/-!
# The tautological point of a coordinate pullback

A coordinate pullback `p : W₂.CoordinateRing →ₐ[F] W₁.FunctionField` — the data underlying an
isogeny `W₁ ⟶ W₂` — sends the two coordinate functions of `W₂` to elements of `F(W₁)`. The
Weierstrass relation is exactly what the coordinate ring quotients out, so the pair solves the
equation of `W₂` over `F(W₁)`, and on an elliptic target that solution is a point. A coordinate
pullback therefore cuts out a point of `W₂⁄F(W₁)`, its *tautological point*, and does so
injectively: evaluating the coordinate ring there recovers the pullback it came from.

The pointedness of an isogeny plays no part in any of this, so everything is stated for a bare
coordinate pullback; an isogeny `φ` uses `φ.pullback.tautologicalPoint`.

For the identity pullback this is the generic point of `W`, of which the construction here is the
pullback-indexed generalisation.

## Main definitions

* `TauCeti.CoordinatePullback.tautologicalPoint`: the point of `W₂⁄F(W₁)` cut out by a coordinate
  pullback.

## Main results

* `TauCeti.CoordinatePullback.tautologicalPoint_ne_zero`: it is an affine point, never the point
  at infinity.
* `TauCeti.CoordinatePullback.evalAlgHom_tautologicalPoint`: evaluating the coordinate ring at it
  recovers the pullback.
* `TauCeti.CoordinatePullback.tautologicalPoint_injective`: a pullback is determined by it.
* `TauCeti.CoordinatePullback.tautologicalPoint_id`: the identity pullback's tautological point is
  the generic point.
-/

public section

open Polynomial WeierstrassCurve.Affine

open scoped Polynomial.Bivariate

namespace TauCeti

open _root_.WeierstrassCurve.Affine

variable {F : Type*} [Field F] {W₁ W₂ : WeierstrassCurve.Affine F}

namespace CoordinatePullback

variable [W₂.IsElliptic]

/-- **The tautological point of a coordinate pullback**: the point of `W₂`, with coordinates in
the function field of `W₁`, cut out by the images of the coordinate functions of `W₂`. They solve
the equation of `W₂` because the Weierstrass polynomial is what the coordinate ring quotients
out. -/
noncomputable def tautologicalPoint (p : CoordinatePullback W₁ W₂) :
    (W₂⁄W₁.FunctionField).toAffine.Point :=
  Point.mk (CoordinateRing.equation_of_algHom p)

/-- **The tautological point is affine**, never the point at infinity. This is what lets consumers
use the coordinate API for nonzero points. -/
theorem tautologicalPoint_ne_zero (p : CoordinatePullback W₁ W₂) : p.tautologicalPoint ≠ 0 :=
  Point.some_ne_zero _

@[simp]
theorem xCoord_tautologicalPoint (p : CoordinatePullback W₁ W₂) :
    Point.xCoord p.tautologicalPoint = p (AdjoinRoot.of W₂.polynomial X) :=
  Point.xCoord_some _

@[simp]
theorem yCoord_tautologicalPoint (p : CoordinatePullback W₁ W₂) :
    Point.yCoord p.tautologicalPoint = p (AdjoinRoot.root W₂.polynomial) :=
  Point.yCoord_some _

-- Not `@[simp]`: the coordinate lemmas above already rewrite the point's coordinates back to the
-- pullback's values, so simp reaches this on its own. It is exported for consumers to name.
/-- **Evaluating the coordinate ring at the tautological point recovers the pullback.** This is
the elimination rule: it turns a statement about the point back into one about the pullback. -/
theorem evalAlgHom_tautologicalPoint (p : CoordinatePullback W₁ W₂) :
    CoordinateRing.evalAlgHom (Point.nonsingular_coords (tautologicalPoint_ne_zero p)).left = p :=
  CoordinateRing.algHom_ext
    (by rw [CoordinateRing.evalAlgHom_of_X, xCoord_tautologicalPoint])
    (by rw [CoordinateRing.evalAlgHom_root, yCoord_tautologicalPoint])

/-- **A coordinate pullback is determined by its tautological point.** The coordinate ring is
generated by its two coordinate functions, so a pullback is fixed by where it sends them. -/
theorem tautologicalPoint_injective :
    Function.Injective (tautologicalPoint (W₁ := W₁) (W₂ := W₂)) := fun p q h =>
  CoordinateRing.algHom_ext
    (by rw [← xCoord_tautologicalPoint, h, xCoord_tautologicalPoint])
    (by rw [← yCoord_tautologicalPoint, h, yCoord_tautologicalPoint])

/-- **The identity pullback's tautological point is the generic point**, of which this
construction is the pullback-indexed generalisation. -/
@[simp]
theorem tautologicalPoint_id (W : WeierstrassCurve.Affine F) [W.IsElliptic] :
    (CoordinatePullback.id W).tautologicalPoint = W.genericPoint := by
  rw [tautologicalPoint, genericPoint_eq_some]
  congr 1
  · rw [CoordinatePullback.id_apply, genericX_def, AdjoinRoot.mk_C]
  · rw [CoordinatePullback.id_apply, genericY_def, AdjoinRoot.mk_X]

end CoordinatePullback

end TauCeti

end
